/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketbooking;

import java.awt.Color;
import static java.awt.Color.red;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import static javafx.scene.paint.Color.color;

/**
 *
 * @author ajmalshah
 */
public class Login_page extends javax.swing.JFrame {
    
    /**
     * Creates new form Login_page
     */
    public Login_page() {
        initComponents();
        signuplogin.setBackground(new Color(0,0,0,70));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        signuplogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        signupLoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cpwd = new javax.swing.JPasswordField();
        cid = new javax.swing.JTextField();
        LoginButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        toadmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        create = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        create_name = new javax.swing.JTextField();
        create_username = new javax.swing.JTextField();
        create_mob = new javax.swing.JTextField();
        create_pwd = new javax.swing.JPasswordField();
        createbutton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        backtologin = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        info = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        signuplogin.setBackground(new java.awt.Color(255, 255, 255));
        signuplogin.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Plan with us. We,");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("* Save your Time.");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("* Manage everything.");

        signupLoginButton.setBackground(new java.awt.Color(255, 0, 0));
        signupLoginButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        signupLoginButton.setForeground(new java.awt.Color(255, 255, 255));
        signupLoginButton.setText("SignUp/Login");
        signupLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupLoginButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/ss.png"))); // NOI18N

        javax.swing.GroupLayout signuploginLayout = new javax.swing.GroupLayout(signuplogin);
        signuplogin.setLayout(signuploginLayout);
        signuploginLayout.setHorizontalGroup(
            signuploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuploginLayout.createSequentialGroup()
                .addGroup(signuploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signuploginLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(signupLoginButton))
                    .addGroup(signuploginLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(signuploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(signuploginLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(signuploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel4)))))
                    .addGroup(signuploginLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        signuploginLayout.setVerticalGroup(
            signuploginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuploginLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(signupLoginButton)
                .addGap(22, 22, 22))
        );

        jPanel3.add(signuplogin, "card2");

        login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("UserName");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password");

        cpwd.setBackground(new java.awt.Color(255, 255, 255));
        cpwd.setForeground(new java.awt.Color(0, 0, 0));
        cpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpwdActionPerformed(evt);
            }
        });

        cid.setBackground(new java.awt.Color(255, 255, 255));
        cid.setForeground(new java.awt.Color(0, 0, 0));
        cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(0, 153, 0));
        LoginButton.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Do not have account?");

        signup.setBackground(new java.awt.Color(204, 0, 0));
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setText("SignUp");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        toadmin.setBackground(new java.awt.Color(255, 255, 255));
        toadmin.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        toadmin.setForeground(new java.awt.Color(153, 0, 0));
        toadmin.setText("Admin? click here");
        toadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toadminMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/11.png"))); // NOI18N

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toadmin)
                    .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(loginLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(signup))))
                .addGap(86, 86, 86))
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpwd)
                    .addComponent(cid))
                .addGap(31, 31, 31))
            .addGroup(loginLayout.createSequentialGroup()
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(LoginButton))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(LoginButton)
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(signup)
                .addGap(38, 38, 38)
                .addComponent(toadmin)
                .addGap(14, 14, 14))
        );

        jPanel3.add(login, "card2");

        create.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Name");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("UserName");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Mobile no");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Password");

        create_name.setBackground(new java.awt.Color(255, 255, 255));
        create_name.setForeground(new java.awt.Color(0, 0, 0));
        create_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_nameActionPerformed(evt);
            }
        });

        create_username.setBackground(new java.awt.Color(255, 255, 255));
        create_username.setForeground(new java.awt.Color(0, 0, 0));
        create_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_usernameActionPerformed(evt);
            }
        });

        create_mob.setBackground(new java.awt.Color(255, 255, 255));
        create_mob.setForeground(new java.awt.Color(0, 0, 0));
        create_mob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_mobActionPerformed(evt);
            }
        });

        create_pwd.setBackground(new java.awt.Color(255, 255, 255));
        create_pwd.setForeground(new java.awt.Color(0, 0, 0));

        createbutton.setBackground(new java.awt.Color(0, 102, 0));
        createbutton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        createbutton.setForeground(new java.awt.Color(255, 255, 255));
        createbutton.setText("Create");
        createbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createbuttonActionPerformed(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Already have an Account?");

        backtologin.setBackground(new java.awt.Color(0, 102, 0));
        backtologin.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        backtologin.setForeground(new java.awt.Color(255, 255, 255));
        backtologin.setText("Login");
        backtologin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtologinActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/add-user-group-woman-man.png"))); // NOI18N

        javax.swing.GroupLayout createLayout = new javax.swing.GroupLayout(create);
        create.setLayout(createLayout);
        createLayout.setHorizontalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createLayout.createSequentialGroup()
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(createLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(create_name, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(create_username, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(create_mob, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(create_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createLayout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(createbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82))))
                    .addGroup(createLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel17)))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backtologin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(82, 82, 82))
        );
        createLayout.setVerticalGroup(
            createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_mob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create_pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(createbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backtologin)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel3.add(create, "card2");

        jPanel1.add(jPanel3);
        jPanel3.setBounds(570, 140, 310, 480);

        ExitButton.setBackground(new java.awt.Color(204, 0, 0));
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("X");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton);
        ExitButton.setBounds(842, 650, 38, 32);

        info.setBackground(new java.awt.Color(204, 0, 0));
        info.setForeground(new java.awt.Color(102, 255, 51));
        info.setText("Info");
        info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoActionPerformed(evt);
            }
        });
        jPanel1.add(info);
        info.setBounds(20, 640, 60, 32);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ticketbooking/ww.jpg"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(0, 0, 900, 700);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        frame = new JFrame ("Exit");
          if(JOptionPane.showConfirmDialog(frame, "COnfirm if you want to Exit","Ticket Booking",JOptionPane.YES_NO_OPTION)==
                JOptionPane.YES_NO_OPTION){
            System.exit(0);
       }
          
    }//GEN-LAST:event_ExitButtonActionPerformed
   
    private void signupLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupLoginButtonActionPerformed
        //To remove/reset the panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //To change the panel
        jPanel3.add(login);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_signupLoginButtonActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
       String username = cid.getText();
        String password = cpwd.getText();
         try{
           
            String databaseURL = "jdbc:mysql://localhost:3306/onlineticket";
            Connection con = DriverManager.getConnection(databaseURL, "root", "firedrone");
            String selectQuery = "select * from customer where username='"+username+"' and password='"+password+"'";
            Statement stat=con.createStatement();    
            ResultSet rs=stat.executeQuery(selectQuery);
            if(rs.next()){
                dispose();
                Bookin_page bp = new Bookin_page();
                bp.setLocationRelativeTo(null);
                bp.setVisible(true);
                JOptionPane.showConfirmDialog(null,"Welcome User!","Ticket Booking", JOptionPane.WARNING_MESSAGE);
               
                
            }
            else{
                JOptionPane.showConfirmDialog(null,"No Account found, please SignUp ","Ticket Booking", JOptionPane.WARNING_MESSAGE);
                cid.setText(null);
                cpwd.setText(null);
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
       
      
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidActionPerformed

    private void cpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpwdActionPerformed

    private void create_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_nameActionPerformed

    private void create_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_usernameActionPerformed

    private void create_mobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_mobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_create_mobActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();
                jPanel3.add(create);
                jPanel3.repaint();
                jPanel3.revalidate();
    }//GEN-LAST:event_signupActionPerformed

    private void createbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createbuttonActionPerformed
         
        String name = create_name.getText();
        String username = create_username.getText();
        String password = create_pwd.getText();
        String mobile = create_mob.getText();
     
        try {
           
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/onlineticket", "root", "firedrone");
            Statement stat = con.createStatement();    
            String selectQuery = "select * from customer where username='"+username+"' and password='"+password+"'";
            System.out.println(selectQuery);
           ResultSet rs=stat.executeQuery(selectQuery);
           System.out.println(rs.next());
           if(rs.next()==true){
             JOptionPane.showConfirmDialog(null,"Account found, please Login ","Ticket Booking", JOptionPane.WARNING_MESSAGE);
           }
           else{
                String insertQuery = "insert into customer values('" + name + "','"+ username + "','" + mobile + "','" + password + "');";
           
                stat.executeUpdate(insertQuery);
                JOptionPane.showConfirmDialog(null,"Account Created!","Ticket Booking", JOptionPane.WARNING_MESSAGE);
                create_name.setText(null);
                create_username.setText(null);
                create_pwd.setText(null);
                create_mob.setText(null);
                jPanel3.removeAll();
                jPanel3.repaint();
                jPanel3.revalidate();
                
       
                jPanel3.add(login);
                jPanel3.repaint();
                jPanel3.revalidate();
            }
          
        }
        catch (Exception e) {
            System.out.println(e);
        }

        
    }//GEN-LAST:event_createbuttonActionPerformed

    private void backtologinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtologinActionPerformed
          jPanel3.removeAll();
          jPanel3.repaint();
          jPanel3.revalidate();
          jPanel3.add(login);
          jPanel3.repaint();;
          jPanel3.revalidate();
          
    }//GEN-LAST:event_backtologinActionPerformed

    private void toadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toadminMouseClicked
       admin a=new admin();
       dispose();
       a.admin();
    }//GEN-LAST:event_toadminMouseClicked

    private void infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoActionPerformed
         JOptionPane.showConfirmDialog(null,"\n\t\t\t\t\tApplication V 1.0\nDesigned and Created by : Ajmal Shah"
                 + " ","Ticket Booking", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_infoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void login(){
        signuplogin.setOpaque(false);
        //signuplogin.setBackground(new  Color(0,0,0,0,));
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton backtologin;
    private javax.swing.JTextField cid;
    private javax.swing.JPasswordField cpwd;
    private javax.swing.JPanel create;
    private javax.swing.JTextField create_mob;
    private javax.swing.JTextField create_name;
    private javax.swing.JPasswordField create_pwd;
    private javax.swing.JTextField create_username;
    private javax.swing.JButton createbutton;
    private javax.swing.JButton info;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel login;
    private javax.swing.JButton signup;
    private javax.swing.JButton signupLoginButton;
    private javax.swing.JPanel signuplogin;
    private javax.swing.JLabel toadmin;
    // End of variables declaration//GEN-END:variables
}
